### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by HikaruIchijyo** [saud-97/TachiyomiS97#15]
### Steps to reproduce

Current crash happens as soon as i click on browse menu.

Started happening as soon as i started restoring backup from yokai

### Expected behavior

It should not crash

### Actual behavior

It is crashing

### Crash logs

FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi.s97, PID: 14924
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
	at com.fredporciuncula.flow.preferences.IntPreference.get(SourceFile:15)
	at eu.kanade.tachiyomi.ui.extension.ExtensionAdapter.<init>(Unknown Source:48)
	at eu.kanade.tachiyomi.ui.extension.ExtensionBottomSheet.onCreate(Unknown Source:12)
	at eu.kanade.tachiyomi.ui.source.BrowseController.onViewCreated(SourceFile:181)
	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(Unknown Source:12)
	at com.bluelinelabs.conductor.Controller.inflate(SourceFile:115)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(SourceFile:186)
	at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:2)
	at com.bluelinelabs.conductor.Router.setBackstack(SourceFile:483)
	at eu.kanade.tachiyomi.ui.main.MainActivity$$ExternalSyntheticLambda5.onNavigationItemSelected(SourceFile:167)
	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(Unknown Source:45)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(SourceFile:15)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(Unknown Source:13)
	at com.google.android.material.navigation.NavigationBarMenuView$1.onClick(Unknown Source:19)
	at android.view.View.performClick(View.java:7570)
	at android.view.View.performClickInternal(View.java:7540)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29721)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### TachiyomiS97 version

1.7.4

### Android version

android 13

### Device

one plus 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have updated all installed extensions.

**Comment by HikaruIchijyo** [comment]
Error upon restoring backup from yokai

FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi.s97, PID: 24439
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
	at com.fredporciuncula.flow.preferences.IntPreference.get(SourceFile:15)
	at com.fredporciuncula.flow.preferences.BasePreference$asFlow$$inlined$map$1$2.emit(SourceFile:65)
	at com.fredporciuncula.flow.preferences.BasePreference$asFlow$$inlined$map$1$2.emit(SourceFile:151)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(SourceFile:128)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Unknown Source:0)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a5500e7, Dispatchers.Main]

**Comment by Saud-97** [comment]
It's an error caused by Yokai Backup settings. Refer to #14 where you may find workarounds.

**Comment by HikaruIchijyo** [comment]
Thanks
